---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Multigroup cTWAS analysis summary

**FINAL**

GTEx && RefZ && TCGA [link](cTWAS_LD_european_combined3_output.html)

+ *GTEx v8 Prostate, Testis, Lymphocytes eQTL+sQTL*

+ *GTEx PredictDB no LD, RefZ and TCGA with LD, cTWAS no LD*

Gene Summary for above analysis [link](cTWAS_LD_european_GENE_SUMMARY.html)

+ *Function in prostate cancer & immunology*

---

Prostate+Testis+Lymphocytes // eQTL+sQTL without LD [link](cTWAS_noLD_european_prostatetestislymphocytes_output.html)

+ Gene Summary for above analysis [link](cTWAS_noLD_european_GENE_SUMMARY.html)

eQTL+sQTL && RefZ with LD [link](cTWAS_LD_european_combined_output.html)

---

Munro et al. 7 QTLs

Prostate [link](cTWAS_LD_european_munro_prostate7_output.html)

Testis [link](cTWAS_LD_european_munro_testis7_output.html)

Lymphocytes [link](cTWAS_LD_european_munro_lymphocytes7_output.html)

Lung [link](cTWAS_LD_european_munro_lung7_output.html)

Liver [link](cTWAS_LD_european_munro_liver7_output.html)

Spleen [link](cTWAS_LD_european_munro_spleen7_output.html)

Fibroblasts [link](cTWAS_LD_european_munro_fibroblasts7_output.html)

Union data visulization [link](cTWAS_union_visualization.html)

---

Overlapped rsid p-values comparison [link](overlapped_pvalue.html)

Prostate+Testis // eQTL+sQTL [link](cTWAS_noLD_european_prostatetestis_output.html)

Prostate+Testis+Lung // eQTL+sQTL [link](cTWAS_noLD_european_prostatetestislung_output.html)

Prostate+Testis+Liver // eQTL+sQTL [link](cTWAS_noLD_european_prostatetestisliver_output.html)

Prostate+Testis+Lymphocytes+Lung // eQTL+sQTL [link](cTWAS_noLD_european_prostatetestislymphocyteslung_output.html)

Prostate+Testis+Lymphocytes+Liver // eQTL+sQTL [link](cTWAS_noLD_european_prostatetestislymphocytesliver_output.html)

---

Small Instestine+Whole Blood // eQTL+sQTL [link](cTWAS_noLD_european_intestinewb_output.html)

Liver // eQTL+sQTL [link](cTWAS_noLD_european_liver_output.html)

Lung // eQTL+sQTL [link](cTWAS_noLD_european_lung_output.html)

Lymphocytes // eQTL+sQTL [link](cTWAS_noLD_european_lymphocytes_output.html)

Lung+Liver // eQTL+sQTL [link](cTWAS_noLD_european_lungliver_output.html)

Lung+Liver+Lymphocytes // eQTL+sQTL [link](cTWAS_noLD_european_lungliverlymphocytes_output.html)
